### PR TITLE
Resolved a NoneType exception during build cleanup.

### PR DESCRIPTION
**Pull request by dinatale2**
In Builder._startBuildFor, it is possible for slavebuilder.slave
to be None for latent slaves, therefore check for None before
releasing locks.

Signed-off-by: Giuseppe Di Natale dinatale2@llnl.gov

### CODE REVIEW

**Comment by dinatale2** [comment]
We previously had a pull request for this (#3), but I don't see a way to reopen it. The ZFS buildbot instance is seeing the "cannot call releaseLocks on a NoneType" exception somewhat frequently. I'm reintroducing a pull request for this because we are hoping to get the ZFS build farm onto our version of buildbot for easier maintenance.

**Comment by morrone** [comment]
OpenSFS's buildbot branch is only for carrying changes that the Lustre build farm needs until we can upgrade to a newer buildbot release that contains needed fixes.  This is not really the right place to land changes for other projects.

**Comment by dinatale2** [comment]
The Lustre buildbot sees this on occasion as well. This fix will benefit it as well.

**Comment by morrone** [comment]
Alright, then.  And since this code is all overhauled and we can just drop this workaround when we upgrade (so it isn't a long term maintenance burden), it is fine to land.

**Pull request merged**
