### PR TITLE
Add url text to the FileUpload build step.

### PR DESCRIPTION
**Pull request by dinatale2**
When specifying a url for the FileUpload build step,
the link text would be the filename provided as part
of the masterdest path. In cases where the filename
is long, this is undesirable. Instead, allow for
a url text to be provided which will be used in place
of the filename in the waterfall view.

Signed-off-by: Giuseppe Di Natale dinatale2@llnl.gov

### CODE REVIEW

**Comment by morrone** [comment]
The only reason that you give for doing this is the filename length.  But this isn't actually saving any width because the source file name appears in the descriptionDone.  So then if it saves no space, I suppose the other reason might be that it looks somewhat redundant to have the file name appear twice in the same box like this:

  uploading
  lustre-2.8.53_20_ga14b4e1.tar.gz
  [lustre-2.8.53_20_ga14b4e1.tar.gz]

I think the idea here is that the file's name at the source and at the destination can be different, so they are listing both.

If we were to remove only one of those, I would think that we would want to remove the filename from the descriptionDone field.  That way the clickable URL remains exactly what we are going to download if we click on it.

**Comment by dinatale2** [comment]
I was constructing a different file path which was much longer previously. Forgot to change the commit message. It is now used to make the link text customizable in general. Maybe this is a useless change now.

**Comment by dinatale2** [comment]
Also, the FileUpload object sets the step status text in its start function and does not ever use description or descriptionDone, which is odd.

**Comment by morrone** [comment]
I'm not clear on what what you mean about a much longer file path.  The path is trimmed out of the displayed message by the call to os.path.basename(), so it should not matter at all whether your path is long or short.  Is that not working?  On the master branch they also call os.path.normpath() first, which might help.

Als, on master they set self.descriptionDone rather than using self.step_status.setText().  I'm not sure that changes anything much for us in practice, but at least it is more clear.

**Comment by dinatale2** [comment]
The filename is what can be long (i.e. I was at one point naming the tarball lustre-src-<full commit hash>.tar.gz) which causes the waterfall display to become distorted. That is why I mentioned filename length. 

I will check master to see how they are setting the description.

**Comment by dinatale2** [comment]
Just updated my branch. Left in the urlText customization. Added code to handle the description. It seems to work, but I'm not convinced I'm handling the description in the best way possible.

**Comment by dinatale2** [comment]
Any thoughts on my recent changes?

**Comment by morrone** [comment]
If you can get them to accept it upstream, then I'm on board.

**Pull request closed without merging**
